### ISSUE TITLE
Mapping between outputs and datacubes

### ISSUE THREAD

**Issue by brandomr** [uncharted-causemos/docs#2]
I'm not sure exactly how `model.outputs` maps to the `datacube` spec. It seems like each [`model.output`](https://github.com/uncharted-causemos/docs/blob/model-schemas/datacubes/model.schema.json#L455-L724) is basically a `feature` that would exist in a `cube`. 

Each `cube` can have multiple features, but I don't see any tie between the `output` `ids` (feature IDs or even names) to a specific `cube`. Will you just infer this by looking at the `feature` column in the `cube` or would you like to add an `array` of `output` `ids` to the `cube` schema?

**Comment by jryu01** [comment]
In my understanding all cubes under same model will have same outputs/features, if that's the case we can safely infer by looking at the feature values from the actual cube data and use output `name` from model metadata to map those together. In this case I think having output `id` in cube spec is less important and I wonder if we even need that. Any thoughts? @mkozlowski-uncharted

**Comment by mkozlowski-uncharted** [comment]
Correct, we assume all cubes for a model will have all the outputs as features.
If we assume that all parameter and output names in a model are unique we could also get rid of the `parameter.id` and `output.id` and just reference by name, this should make the cube metadata much more human readable.
