### ISSUE TITLE
Loosen requirements on `parameter.choices`

### ISSUE THREAD

**Issue by brandomr** [uncharted-causemos/docs#3]
We have encountered situations where the `choices` for a parameter might be unbound. For example, we created a model that relies on searches of Google Trends. These can be arbitrary, but they are `str` type parameters.

Additionally, some models have enumerated `choices` for things that are not `str`. 

I think it would be preferable (and would simplify the schema) to make `choices` optional for any parameter type and required for none. 

> Note: it is currently required for `str` and not seemingly allowed (?) for other types.

**Comment by brandomr** [comment]
I'm actually generally not a fan of all the `if/then` logic around `type` in the schema since I think it makes it quite complicated. I know that Galois had considered it important, but if it's not critical for you I'd suggest we remove it. We can be flexible on this though.

**Comment by mkozlowski-uncharted** [comment]
I'm in favour of getting rid of the `if/then` logic. I'll make `choices`, `min`, and `max` optional.
In order to support unbounded parameters I will add a "freeform" option to the `data_type` enum. This might be a challenge to expose visually however.
